language: java

jdk:
  - openjdk11
  

addons:
  sonarcloud:
    projectKey: "spotify-ap"
    organization: "sigrist-github"
    login: $TRAVIS_KEY 

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
